Raster reader function with compliant resolution and extent functions.
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #115
Opened 2022-09-05 11:31 UTC by jamesgyoung

Pull request to partially work towards and complete the issues #107  and #108 

The main function added, `read_dataset_from_file` in `raster.py` uses xarray to open rasters. 
The data and metadata of the input raster is used to check whether the data needs to be resampled, reshaped or both.
The functions that check and manipulate the data are in `_raster.py`.

usage:

```python
from sds_data_model.raster import read_dataset_from_file

# auto reads the entire file (i.e. every band), here band 1 is specified
# nodata value provided here as the metadata of the file uses `None`
single_band_dataset = read_dataset_from_file("lcmgb2015.tif", band=[1], categorical=True, nodata=0)
```
The variable `single_band_dataset` is an xarray.Dataset that contains two variables. A DataArray of the raster band data and a `Coordinates` variable called `spatial_ref` which has metadata for the raster in its `.attrs` attribute.

TODO:
- [x] Tests - Create new issue for this.
- [x] Refactor into a class `DatasetWrapper` - Abstract #107 into a new issue.
- [x] ~Multiband reading~
- [ ] Read metadata/graph sidecar - Add this item from #108 into a separate issue.
- [x] ~Fix nodata metadata after manipulation~ 
- [x] ~Add coordinate variables~

2022-09-27 10:17 UTC, EFT-Defra requested changes
This works (as far as I can tell) and is very performant but it needs more work to be maintainable. I think you need to include full docstrings for all these functions and add a suite of tests. I've submitted a pull request #126 to get you started.

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/raster.py
> +    decode_coords: Union[bool, None, Literal["coordinates", "all"]] = "all",
Use `Optional` for a `Union` that could be `None`:

```suggestion
    data_path: str,
    band: Optional[List[int], List[str]] = None,
    categorical: Union[bool, Sequence[bool]] = False,
    nodata: Optional[float] = None,
    engine: Optional[str] = None,
    decode_coords: Optional[Union[bool, Literal["coordinates", "all"]]] = "all",
```

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/raster.py
> +    """
For new code, the docstring should include:

- A single line description (<= 80 characters)
- An example
- A description of each argument
- A description of the return type

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/raster.py
> +    )
There's nothing wrong with this by I prefer to distinguish between variables provided by the caller and variables created within the function, so I'd have gone for something like:

```suggestion
    if engine:
        _engine = engine
    elif suffix == ".zarr":
        _engine = "zarr"
        _decode_coords = decode_coords
    elif suffix[1:] in raster_driver_extensions().keys():
        _engine = "rasterio"
        _decode_coords = None
  
    dataset = open_dataset(
        data_path,
        engine=_engine,
        decode_coords=_decode_coords,
        mask_and_scale=False,
    )
```

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +        return None
Is there a reason this doesn't just return `True` or `False`? If it can, I'd suggest renaming it to a closed question like `_has_wrong_cell_size` to make it clear that it's going to return a Boolean.

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +        return None
Same as `_check_cellsize`: Is there a reason this doesn't just return `True` or `False`? If it can, I'd suggest renaming it to a closed question like `_has_wrong_shape` to make it clear that it's going to return a Boolean.

Additionally, do you need to check the shape and the transform or could you just check the transform?

And, can this test be done at the dataset level?

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    )
We discussed this yesterday and I think your opposition is valid but I'm putting this here for the record: Should this be limited to only `categorical` data or could it apply to all `int` data types?

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    band: Union[List[int], List[str], None] = None,
I think this should be `bands` as it's a collection. Also, I think the type should be Optional

```suggestion
    bands: Optional[Union[List[int], List[str]]] = None,
```

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    return data_arrays
I'm not sure I understand what you're doing here, so a docstring and comments would help. Also, is it possible to retrieve the band of the band (if one exists), instead of renaming it with the index?

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    band: Union[List[int], List[str], None] = None,
Same as `_select_data_arrays`: I think this should be bands as it's a collection. Also, I think the type should be Optional

```suggestion
    bands: Optional[Union[List[int], List[str]]] = None,
```

2022-09-27 10:17 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    categorical: Union[bool, Sequence[bool]] = False,
As discussed, I think this should be a single `bool` if all the bands are categorical or a mapping of bands and `bool`s, this reduce the possibility of the list of bands and the list of categoricals getting out of sync

2022-09-28 15:00 UTC, EFT-Defra commented
TODO:

- [x] Merge your pull request
- [x] Write docstrings
- [x] Refactor handling of bands/categorical (i.e. use dict)
- [x] Move read_dataset_from_file into _raster.py
- [x] Create DatasetWrapper class that has a method that uses, read_dataset_from_file,
- [x] Review tests
- [x] Review any further suggestions you've made on the pull request
- [x] Renaming a coordinates when we don't reshape
- [x] Use `long_name` from `attrs` to rename band if it exists

2022-10-04 11:00 UTC, EFT-Defra requested changes
Please make the changes to your docstrings requested below.

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    """
use `:func:` to reference another function in a docstring.

```suggestion
    Returns:
        bool: An indication in :func:`_resample_and_reshape` whether to resample data.
    """
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    input transform are **not equal** to the expected cell size.
This should be a one line (<88 character) description of the function and you should need to use `\` to break a line in a multiline docstring. You can add more information in the optional description paragraph.

```suggestion
    """Return `True` if the cell size is not what is expected.
    
    Return `False` if either the x (a) and y (e) values of the input transform do
    **not equal** the expected cell size.
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    is **not equal** to the expected shape.
As above, the first line of a function docstring should should be a one line (<88 character) description of the function.

```suggestion
    """Return true if the shape/extent is **not equal** to the expected shape.
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +        bool: An indication in `_resample_and_reshape` whether to reshape/regrid data.
As above, use `:func:` to reference another function in a docstring.

```suggestion
        bool: An indication in :func:`_resample_and_reshape` whether to reshape/regrid data.
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    the updating of shape/extent/transform.
As above, the first line of a function docstring should should be a one line (<88 character) description of the function.

```suggestion
    """An intermediate `DataArray` constructor for updating the shape/extent/transform.
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    """
1. The return type should include a description.
2. You can add a link to the OpenCV project to the docstring like this:

```suggestion
    """Returns a `DataArray` with scaled/resampled data using `OpenCV`_.

    Args:
        data_array (DataArray): Input `DataArray`.
        expected_cell_size (int): New cell size for data. Acts as the resampling factor.
        categorical (bool): Determines which resampling/interpolation is used.
            Set to False will use bilinear. Set to True will use nearest-neighbour.

    Returns:
        DataArray: a `DataArray` with scaled/resampled data.
    
    .. _`OpenCV`:
        https://github.com/opencv/opencv-python    
    """
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +        )
You should always try and use the most precise exception possible which, in this case, I think is [`ValueError`](https://docs.python.org/3/library/exceptions.html#ValueError). 

```suggestion
    Raises:
        ValueError: If the `nodata` arg is `None` and the input `DataArray`
            does not have a nodata value (that is not equal to None).
    """
    if nodata is not None:
        data_array.rio.write_nodata(nodata, inplace=True)
    elif data_array.rio.nodata is None:
        raise ValueError(
            "Input dataset does not have a nodata value. One must be provided."
        )
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    inserted into a grid of shape (`expected_y_max`, `expected_x_max`).
As above, the first line of a function docstring should should be a one line (<88 character) description of the function.

```suggestion
    """Inserts the input `data_array` into a `expected_y_max` * `expected_x_max` grid.
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +        expected_y_max (int): y maxium (height). Defaults to BNG_YMAX.
maximum is missing an "m".

```suggestion
        expected_y_max (int): y maximum (height). Defaults to BNG_YMAX.
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +        expected_y_max (int): y maxium (height).
maximum is missing an "m".

```suggestion
        expected_y_max (int): y maximum (height).
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/_raster.py
> +    of the input `Dataset` against the input values.
As above, the first line of a function docstring should should be a one line (<88 character) description of the function.

```suggestion
    """Resamples and/or reshapes a `Dataset` with the wrong extent or cell size.
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/raster.py
> +    """#TODO DatasetWrapper class documentation."""
How about this as a place holder instead of the #TODO

```suggestion
    """A wrapper for an `xarray.dataset`."""
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/raster.py
> +                )
You can intermingle code blocks and comments in an example block.

```suggestion
        Examples:
            Read 2 bands from raster, specifying that the first is categorical.

            >>> dset_wrap_from_tif = DatasetWrapper.from_files(
                    data_path="3_band_raster.tif",
                    bands=[1, 2],
                    categorical={1: True, 2: False},
                )

            Read 2 bands from raster, specifying both are categorical.

            >>> dset_wrap_from_zarr = DatasetWrapper.from_files(
                    data_path="multiband_raster.zarr",
                    bands=["classification", "code"],
                    categorical=True
                )
```

2022-10-04 11:00 UTC, EFT-Defra commented on src/sds_data_model/raster.py
> +            DatasetWrapper
The return type should include a description.

```suggestion
            _DatasetWrapper: A thin wrapper around an `xarray.Dataset` containing
                `xarray.DataArray with 10m cell size and British National Grid extent.
```

2022-10-04 11:04 UTC, EFT-Defra commented
The automated checks were failing so I made the following changes:

- I updated the poetry lock file (https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/115/commits/3c44287f59967fdcd1a1c17434147cbee4fc9e3d)
- Then I gave `DatasetWrapper.from_files` a return type (https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/115/commits/d85f384dd8a2f3d7ffcc80c7dbb728cc153b4905)
- Finally, I switched the `mypy` dependency from dev to latest (https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/115/commits/a4afd60600649c377fe34aff21d995bc43b9080c)

I also added tests for datasets on a smaller grid (https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/115/commits/e6ab26b1286207037c5732278abc1748c93d2399)

2022-10-04 13:18 UTC, jamesgyoung commented
@EFT-Defra, thanks for the suggestions. I've now added them.

2022-10-04 13:48 UTC, EFT-Defra approved these changes
Excellent, great work @JamesKeny0n 🎆 🎆🎆

2022-10-04 13:48 UTC, merged