Spark DataFrameWrapper : `from_files` alternative constructor and `call_method` method
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #136
Opened 2022-10-06 11:36 UTC by lara56

2022-10-18 10:57 UTC, lara56 commented
Overview. Closes #106  and #127 
Code to add include spark functionality, including from_files method, call_method, and tests for these functions. This pull request also includes to_zarr method, but this should be reviewed separately. 

To review:
- all files and code, just excluding dataframe.py, line 210 onwards which is the to_zarr method.

2022-10-19 12:16 UTC, EFT-Defra requested changes
As discussed, I have resolved the merge conflicts and push my refactoring of your tests for the `.call_method`. Most of my comments and suggests relate to `mypy` but you'll also need to resolve any formatting or linting issues identified by the automated checks.

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +from pyspark.pandas import DataFrame, read_excel
Do you still need to import the Pandas on Spark DataFrame? If so, alias as follows to avoid name collision with the actual `pandas DataFrame`:  

```suggestion
from pyspark.pandas import DataFrame as SparkPandasDataFrame
from pyspark.pandas import read_excel
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +from pandas import DataFrame
It's probably safest to alias this one too:

```suggestion
from pandas import DataFrame as PandasDataFrame
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +spark = SparkSession.getActiveSession()
Do you still need this?

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            data = data.to_spark()
`mypy` isn't happy here because `file_reader_pandas[suffix_data_path](data_path, **read_file_kwargs)` could return a `DataFrame`, a `Series`, or an `OrderedDict` and, if it's the latter, there won't be a `.to_spark` method to call. You can fix this by checking the type of `data` before calling the `.to_spark` method.

Also, when you finally pass `data` to the class constructor it will need to be a ` SparkDataFrame`. However, as mentioned above, the functions in `file_reader_pandas` can return several types. I would, therefore, make the initial assign to a different variable, check it's type and then, if it's not an `OrderedDict`, assign it to the `data` variable.  Unfortunately, the `.to_spark` returns either a `SparkDataFrame` or `Any`, so, to silence `mypy` you'll need to explicit annotate `data` as a ` SparkDataFrame`.

```suggestion
        if suffix_data_path in file_reader_pandas.keys():
            spark_pandas_data = file_reader_pandas[suffix_data_path](data_path, **read_file_kwargs)
            if isinstance(spark_pandas_data, SparkPandasDataFrame,) or isinstance(
                spark_pandas_data,
                SparkPandasSeries,
            ):
                data: SparkDataFrame = data.to_spark()
```

You need to alias `pyspark.pandas.DataFrame` as `SparkPandasDataFrame` and import `pyspark.pandas.Series` and alias that as `SparkPandasSeries`.

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            data = file_reader_spark[suffix_data_path](data_path, **read_file_kwargs)
`mypy` doesn't like this because it doesn't know what `file_reader_spark` is, you can help it out by adding a type annotation to the assignment on line 113: `file_reader_spark = {` should be `file_reader_spark: Dict[str, Callable] = {`. In other words, `file_reader_spark` is a mapping of strings to things-that-can-be-called i.e. functions. 

You'll need to  import `Callable` from `typing`.

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +    ) -> Optional[Self]:
It looks like `mypy` still isn't down with `Self` so this will need to be:
```suggestion
    def call_method(
        self: _DataFrameWrapper,
        method_name: str,
        /,
        *args,
        **kwargs,
    ) -> Optional[_DataFrameWrapper]:
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            return return_value
I'm not sure about this last bit any more. I was thinking about the [DataFrame APIs](https://spark.apache.org/docs/3.1.1/api/python/reference/pyspark.sql.html#dataframe-apis) that return a new DataFrame, such as `.limit` or that return `None` but enact some side effects, such as `.display` but that's not the whole story. For one, there's methods like `.agg` that return `GroupedData`, which we probably want to treat like a `DataFrame`, because the caller will probably want to call another method on it like `.summarise`. There may be other cases we need to consider. Can you look at the return types of the different DataFrame APIs and find out if there are any others we need to handle?

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +        """Calls spark method specified by user on spark dataframe in wrapper, using user specified arguments.
This line is too long, it should be a single line, i.e. <88 characters.

Also, I would use `pyspark.sql.DataFrame` or Spark `DataFrame`.

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +        THe function:
There should be a space after the first line and the "H" should be lower case.

```suggestion

        The function:
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +                        read_file_kwargs = {'suffix':'.shp',  'ideal_chunk_size':1000})
- Variables should be lowercase, only classes are capitalised in Python.
- You don't need the `ideal_chunk_size`, it's only relevant if you're using the rows concurrency strategy, which you aren't, and it's 1,000 by default anyway.

```suggestion
            >>> wrapped = DataFrameWrapper.from_files(
                name = "National parks",
                data_path="/dbfs/mnt/base/unrestricted/source_defra_data_services_platform/dataset_traditional_orchards/format_SHP_traditional_orchards/LATEST_traditional_orchards/",
                read_file_kwargs = {'suffix':'.shp'})
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            >>> Wrapped_small =  DataFrameWrapper.call_method(df_wrap,  method_name = 'limit', num = 8)
- The text says 5 but you pass 8.
- As above, variables should be lowercase.
- Though you can call `call_method` as a function, as you are below, it kind of defeats the purpose of a method. Call `.call_method` on `wrapped` instead, then you don't have to supply the DataFrameWrapper instance.
- The "/" in the method signature means that everything before it is a positional argument and cannot be called as a keyword argument, so calling `method_name="limit"` would raise an error, just call `"limit"` instead.  

```suggestion
            Limit number of rows to 5
            >>> wrapped_small =  wrapped.call_method('limit', num = 5)
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            >>> Wrapped_small.data.show()
- As above, variables should be lowercase.
- Explicitly calling the `.show` method of the `data` attribute bypasses `call_method`. Instead, you should be calling `.call_method("show")`.

```suggestion
            >>> wrapped_small.call_method("show")
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            self (Self): Spark DataFrame
- As noted above, `mypy` doesn't like `Self` unfortunately, so we'll have to revert to the `_DataFrameWrapper` type variable.
- Also, self here is a DataFrameWrapper instance, not a Spark DataFrame

```suggestion
            self (_DataFrameWrapper): Spark DataFrameWrapper
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            Optional[Self]: Spark Dataframe or property output
- As noted above, `mypy` doesn't like `Self` unfortunately, so we'll have to revert to the `_DataFrameWrapper` type variable.
- Also, the output is an updated DataFrameWrapper instance, not a Spark DataFrame

```suggestion
            Optional[Self]: Updated Spark DataFrameWrapper or property output
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +        wrapped with associated metadata
First line is too long. Should be <88 characters.

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +                                       )
You don't need the `ideal_chunk_size`, it's only relevant if you're using the rows concurrency strategy, which you aren't, and it's 1,000 by default anyway.

```suggestion
        >>> wrapped_shp = DataFrameWrapper.from_files(name = "National parks",                               
                                        data_path="/dbfs/mnt/base/unrestricted/source_defra_data_services_platform/dataset_national_parks/format_SHP_national_parks/LATEST_national_parks/",
                                        read_file_kwargs = {'suffix':'.shp'},
                                        metadata_path =  "https://ckan.publishing.service.gov.uk/harvest/object/656c07d1-67b3-4bdb-8ab3-75e118a7cf14"
                                       )
```

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +                                       )
- Did you mean to assign to `check_csv` then `wrapped_csv`?
- Can you find a path to a CSV that doesn't include James' email address?

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            metadata_path (Optional[str], optional): _description_. Defaults to None.
`_description_` should be replaced with a description.

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +            _DataFrameWrapper: _description_
`_description_` should be replaced with a description.

2022-10-19 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +        #need to replace spark with _spark
No you still need these comments?

2022-10-19 12:16 UTC, EFT-Defra commented on tests/test_DataFrameWrapper.py
> +
I'd construct a Spark DataFrame directly, see below.

```suggestion
```

2022-10-19 12:16 UTC, EFT-Defra commented on tests/test_DataFrameWrapper.py
> +
- As mentioned above, I'd cut out the middleman and create a Spark DataFrame directly.
- This means moving your `expected_schema` definition forward
- Also, as your expected DataFrame has integer we should really be testing for integers. See below for how to stop Spark from treating the columns as strings. 

```suggestion


@fixture
def expected_schema() -> StructType:
    return StructType(
        [
            StructField("a", IntegerType(), True),
            StructField("b", IntegerType(), True),
            StructField("c", IntegerType(), True),
        ]
    )


@fixture
def expected_dataframe(
    spark_session: SparkSession,
    expected_schema: StructType,
) -> SparkDataFrame:
    data = [
        {"a": 1, "b": 4, "c": 7},
        {"a": 2, "b": 5, "c": 8},
        {"a": 3, "b": 6, "c": 9},
    ]
    return spark_session.createDataFrame(
        data=data,
        schema=expected_schema,
    )


```

2022-10-19 12:16 UTC, EFT-Defra commented on tests/test_DataFrameWrapper.py
> +    return p
- The `pytest` docs recommend `tmp_path` over `tmpdir` and `tmpdir_factory`, which is my fault as I suggested `tmpdir`.
- You might as well return a string here as you're going to need to convert it to use it
- I don't think test functions need a full docstring, just a oneliner.
- Also, I prefer `temp_path` because your'e returning a path not a file

```suggestion
@fixture
def temp_path(tmp_path, expected_dataframe: SparkDataFrame) -> str:
    """Create a temporary directory and data for testing."""
    path = str(tmp_path / "test.csv")
    expected_dataframe.write.csv(
        path=path,
        header=True,
    )
    return path
```

2022-10-19 12:16 UTC, EFT-Defra commented on tests/test_DataFrameWrapper.py
> +
I'd move this earlier, see above.

```suggestion
```

2022-10-19 12:16 UTC, EFT-Defra commented on tests/test_DataFrameWrapper.py
> +    assert_df_equality(received.data, expected_spark)
- `temp_path` is a string now
-  comparing the `.data.schema` attribute is unnecessary because `assert_df_equality` checks schema equality, so `expected_schema` isn't required.
- We're defining `expected_spark` as a fixture now, so we don't need to define it within the function
- Passing `read_file_kwargs={"header": True, "inferSchema": True},` appears to get Spark to recognise that the integers are integers.

```suggestion
def test_vector_layer_from_files(
    spark_session: SparkSession,
    temp_path: str,
    expected_name: str,
    expected_dataframe: SparkDataFrame,
    expected_metadata: None,
) -> None:
    """Reading test data returns a DataFrameWrapper with expected values."""
    received = DataFrameWrapper.from_files(
        spark=spark_session,
        data_path=temp_path,
        read_file_kwargs={"header": True, "inferSchema": True},
        name="Trial csv",
    )

    assert received.name == expected_name
    assert received.metadata == expected_metadata
    assert_df_equality(received.data, expected_dataframe)
```

2022-10-20 10:40 UTC, lara56 commented
I have pushed up latest changes which hopefully address your points. 
A few things:
1) for my code section (excluding to_zarr related code) I think all the tests are passing apart from 2 which I'm struggling to fix. This is:
-  Incorrect indentation on line 63 of _dataframe.py which I have re-done multiple times and its still not happy, and 
- Missing docstring in public module, as couldn't work out how to fix. 
2) I know *args and **kwargs in call_method needs types, but when I added them in, I kept having issues and didn't have time to resolve, so can review that next week. 

Apart from that, hopefully everything should be working.

2022-10-20 13:22 UTC, EFT-Defra commented
> Incorrect indentation on line 63 of _dataframe.py which I have re-done multiple times and its still not happy

I've fixed this in https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/136/commits/5c1cfc171d37013cc6221944b6f5515fdaa23b86, the problem was that the second line needed a hanging indent:

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/5c1cfc171d37013cc6221944b6f5515fdaa23b86/src/sds_data_model/_dataframe.py#L67-L68

> Missing docstring in public module, as couldn't work out how to fix.

I've fixed these in https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/136/commits/93679402a8ad3d416615514d9b54e73b40e819b5, https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/136/commits/1fee73c6bc4e5ec182349687c037c19c8fd7f40b and https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/136/commits/8a73d72b7cac3ca1ea761a57dc1c17d9929643ee.

Basically, you just need to add a multi-line (i.e. triple-double quote) to the first line. For example:

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/5c1cfc171d37013cc6221944b6f5515fdaa23b86/src/sds_data_model/_dataframe.py#L1

> I know *args and **kwargs in call_method needs types, but when I added them in, I kept having issues and didn't have time to resolve, so can review that next week.

This is a tricky one. A specification for typing `*args` and `**kwargs` was proposed in [PEP 612](https://peps.python.org/pep-0612/) and was introduced in Python 3.10 but we're using Python 3.8 so that doesn't help us. The work around is to use close-enough typing as I did in https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/commit/41bc53967f87090b2da220c8657e100bf28660bf, e.g.:

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/41bc53967f87090b2da220c8657e100bf28660bf/src/sds_data_model/dataframe.py#L149-L150

Excellent work though, aside @PiumiA's `to_zarr` work, this is ready to merge!

2022-10-25 18:36 UTC, EFT-Defra approved these changes

2022-10-25 18:36 UTC, merged