Failing to read GEMINI metadata with missing language
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #150
Opened 2022-10-13 13:23 UTC by jpd-defra

Fixes #147

Hoping this minor ammendment allows misisng values in metadata to pass through without erroring.

2022-10-17 15:52 UTC, jpd-defra commented
@EFT-Defra - I've wrestled with trying to satisfy the checks but haven't got there. For now, if you could check the validity of my approach (i.e. changes to `_get_value` and `_get_values`, that would be appreciated please.

2022-10-19 16:05 UTC, EFT-Defra requested changes
As mentioned, I added a test in 5ba83f02db05d582094528d15546657764e70218 and some suggestions about how to placate `mypy`.

2022-10-19 16:05 UTC, EFT-Defra commented on src/sds_data_model/metadata.py
> +) -> Union[str, None]:
`Union[T, None]` (where T is a type) is so common that it has a special syntax: `Optional[T]`, so this should be:

```suggestion
) -> Optional[str]:
```

2022-10-19 16:05 UTC, EFT-Defra commented on src/sds_data_model/metadata.py
> +        target_element: str = target_elements[0].strip()
`mypy` is complaining because your annotating `target_element` on line 181 after you've first defined it on line 179. As the return type of this function is now `Optional[str]`, you shouldn't need to assert that `target_element` is string here anymore. 
```suggestion
    if not target_elements:
        target_element = None
    else:
        target_element = target_elements[0].strip()
```

2022-10-19 16:05 UTC, EFT-Defra commented on src/sds_data_model/_vector.py
>          raise ValueError("If there isn't any metadata, a name must be supplied.")
`mypy` doesn't seem to recognise the nested returns here and is complaining. One solution would to nested assignments followed by a final return:

```suggestion
    if name:
        _name = name
    elif metadata:
        if metadata.title:
            _name = metadata.title
        else: 
            ValueError("Metadata provided, but no title present, a name must be supplied.")
    else:
        raise ValueError("If there isn't any metadata, a name must be supplied.")
    return _name
```

2022-10-19 16:05 UTC, EFT-Defra commented on src/sds_data_model/metadata.py
> +    or list of lists of strings.
This line is too long, how about:

```suggestion
    """`XPath`_ query from a string, list of strings, or list of lists of strings.
```

2022-10-20 08:03 UTC, jpd-defra commented
Thanks for adding the test and offering some advice on Typing/mypy. I'm slowly getting it... 

3 of your suggestions could be implemented with the click of a button whereas the fourth required manual amendment, but seems to have worked. 

Hopefully this is ready for a merge.

2022-10-20 13:51 UTC, EFT-Defra commented
I made a few small changes to satisfy the checks:

1. I added docstrings to the new fixtures (that I added) in https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/150/commits/03809df61267f114be4f4c6cf6f55dba93668af6

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/03809df61267f114be4f4c6cf6f55dba93668af6/tests/test_metadata.py#L10-L13

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/03809df61267f114be4f4c6cf6f55dba93668af6/tests/test_metadata.py#L69-L72

2.  I told `flake8` to ignore the line length of the URL in the `_get_xml` docstring by adding `B950` the "line too long" code to the codes to ignore in https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/150/commits/4261b9c4392166f63a9f86d5ea7c7e0d2964a0e9

https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/4261b9c4392166f63a9f86d5ea7c7e0d2964a0e9/src/sds_data_model/metadata.py#L238-L242

3. I ran `poetry run nox -t format` to format the files with `black` and `isort` locally in https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/pull/150/commits/51f2b40fab94ff7ce46d04531c65eb57aeaa9230.

2022-10-20 13:51 UTC, merged