Jpd defra/issue189
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #193
Opened 2022-11-18 09:08 UTC by jpd-defra

Fixes #189.

- Introduces a new hidden function `_check_for_zarr`. This function takes a directory path and tries to read in a zarr from that directory. If successful, True is returned, and if not, False. 
- This was my first time using `try` and `except`, and I'm unsure if it's implemented correctly, despite behaviour being as expected.
-  `_check_for_zarr` forms part of some new code at the beginning of the `to_zarr` method. In combination with the value of the new `overwrite` flag (defaults to False), there are 3 outcomes:

1. If overwrite is False and a zarr is found an error is thrown.
2. If overwrite is True and a zarr is found, a message is provided and the function continues.
3. If overwrite is True/False and no zarr is found, the function continues.

After experimenting with the write modes of zarr, I decided it was better to deal with checking for existing zarrs before launching into the 'Spark' parts of the code, as this can take several minutes. Dealing with it beforehand, throws an immediate error (if appropriate). 

Documentation has also been updated, and if it's agreed this is the write approach, I will think about how to add a test for this.

2022-11-21 17:02 UTC, jpd-defra commented
Now includes a test to check that an error is thrown when a directory containing a zarr is chosen as an output path and `overwrite = False`.

2022-11-22 12:16 UTC, EFT-Defra requested changes
3 minor changes, please! Otherwise, good work!

2022-11-22 12:16 UTC, EFT-Defra commented on src/sds_data_model/dataframe.py
> +        #    _path = _path.with_suffix("")
Remove this is if you're not going to use it.

If you've got a good reason to keep it, commented out, in the source code, write a comment explaining why you're keeping it, 

  ```suggestion
```

2022-11-22 12:16 UTC, EFT-Defra commented on tests/test_DataFrameWrapper.py
> +        str("hl.zarr"),
You shouldn't need to `str` a string but I think you do need to provide the `argvalues` as tuples, even if they've only got one value. e.g.:

```suggestion
        ("",),
        ("hl.zarr",),
```

2022-11-22 12:16 UTC, EFT-Defra commented on tests/test_DataFrameWrapper.py
> +        "out_zarr",
The `ids` are just for us, so they can be more human-friendly, how about:

```suggestion
        "directory",
        ".zarr file",
```

2022-11-23 08:59 UTC, merged