Create dataclass for aspatial data
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #21
Opened 2022-06-24 13:01 UTC by danlewis85

Note that we've chosen to simply the task to creating a dataclass for relatively simple rectangular data, creating a dataclass called `TableLayer`. This pull request closes #9 

The following gives some context for how the dataclass and its methods could be used:
```python
from sds_data_model.table import TableLayer
```
A `TableLayer` can be created from an url using the `from_file` class method as follows:
```python
url = 'https://www.ons.gov.uk/file?uri=/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/smallareaincomeestimatesformiddlelayersuperoutputareasenglandandwales/financialyearending2018/netannualincomeafterhousingcosts2018.csv'

income = TableLayer.from_file(data_path = url,
                              data_kwargs = {'skiprows': 4},
                              name='Net annual income after housing costs 2018')
```
This creates a `TableLayer` object named `income`, methods can then be called to manipulate the object:
```python
# Select some columns
income = income.select(['MSOA code', 'MSOA name', 'Net annual income after housing costs (£)'])

# Fix numerical column
income = (income
          .replace('Net annual income after housing costs (£)', ",", "")
          .to_numerical('Net annual income after housing costs (£)'))

# Filter rows
income = income.where(income.df['MSOA code'].str.startswith('E'))

# Query rows 
income.query("`MSOA name` == 'County Durham 005'").df
```

A `TableLayer` can also be constructed directly:
```python
import pandas
from sds_data_model.metadata import Metadata

lookup = pandas.DataFrame(data = [[1, 'Broadleaved, mixed & yew woodland'],
                                  [2, 'Coniferous woodland'],
                                  [3, 'Arable and horticulture'],
                                  [4, 'Improved grassland'],
                                  [5, 'Neutral grassland'],
                                  [6, 'Calcareous grassland'],
                                  [7, 'Acid grassland'],
                                  [8, 'Fen, marsh and swamp'],
                                  [9, 'Heather'],
                                  [10, 'Heather grassland'],
                                  [11, 'Bog'],
                                  [12, 'Inland rock'],
                                  [13, 'Saltwater'],
                                  [14, 'Freshwater'],
                                  [15, 'Supra-littoral rock'],
                                  [16, 'Supra-littoral sediment'],
                                  [17, 'Littoral Rock'],
                                  [18, 'Littoral sediment'],
                                  [19, 'Saltmarsh'],
                                  [20, 'Urban'],
                                  [21, 'Suburban']],
                          columns=['code', 'landcover_name'])

landcover_meta = Metadata(title='landcover lookup',
                          dataset_language=("eng"),
                          abstract='Lookup for UKCEH landcover map raster classes',
                          topic_category=(None),
                          keyword=('landcover'))

# Construct TableLayer
landcover_lookup = TableLayer(name="landcover lookup", df=lookup, metadata=landcover_meta)
```

2022-07-01 09:35 UTC, EFT-Defra commented on src/sds_data_model/table.py
> +        data_kwargs: Optional[Dict[str, Any]] = {},
```suggestion
        data_kwargs: Optional[Dict[str, Any]] = None,
```
As this is optional, why not use `None` instead of an empty `dict`

2022-07-01 09:37 UTC, EFT-Defra commented on src/sds_data_model/table.py
> +                       ".xls": read_excel,
```suggestion
                       ".xls": read_excel,
                       ".xlsm": read_excel,
                       ".xlsb": read_excel,
                       ".odf": read_excel,
                       ".ods": read_excel,
                       ".odt": read_excel, 
```
[pandas.read_excel](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html) supports several other file types, so we might as well include them too

2022-07-01 11:18 UTC, EFT-Defra commented on src/sds_data_model/table.py
> +            df = file_reader[suffix](data_path, **data_kwargs)
Is this necessary?

For the example you give in the comments, you can read read directly from the url if you supply an `encoding` argument and a `User-Agent` header to pass on to the underlying GET request, e.g.:

```python
url = 'https://www.ons.gov.uk/file?uri=/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/smallareaincomeestimatesformiddlelayersuperoutputareasenglandandwales/financialyearending2018/netannualincomeafterhousingcosts2018.csv'

income = TableLayer.from_file(
    data_path = url,
    data_kwargs = {
        'skiprows': 4,
        "encoding": "ISO-8859-1",
        "storage_options": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.39",
        }
    },
    name='Net annual income after housing costs 2018',
)
```

2022-07-01 11:30 UTC, EFT-Defra commented on src/sds_data_model/table.py
> +        return numeric_output
Similarly, are these necessary?

For the example you give in the comments, you can read read directly from the URL if you supply an `thousand` separator argument, e.g.:

```python
url = 'https://www.ons.gov.uk/file?uri=/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/smallareaincomeestimatesformiddlelayersuperoutputareasenglandandwales/financialyearending2018/netannualincomeafterhousingcosts2018.csv'

income = TableLayer.from_file(
    data_path = url,
    data_kwargs = {
        'skiprows': 4,
        "encoding": "ISO-8859-1",
        "thousand":",",
        "storage_options": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.39",
        }
    },
    name='Net annual income after housing costs 2018',
)
``` 

For more complex transformations, you could provide a `converter` argument instead, e.g.:

```python
income = TableLayer.from_file(
    data_path = url,
    data_kwargs = {
        'skiprows': 4,
        "encoding": "ISO-8859-1",
        "converters": {
            "Net annual income after housing costs (£)": lambda x: int(x.replace(",", ""))
        },
        "storage_options": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.39",
        }
    },
    name='Net annual income after housing costs 2018',
)
```

However, this would mean we need to capture the `data_kwargs` passed to the initial `from_files` method...

2022-07-01 11:36 UTC, EFT-Defra commented on src/sds_data_model/table.py
> +    return code_input
As you suspected, you can do this in less lines with regex. 

```suggestion
def _get_function_input(func_name: str, frame: inspect.types.FrameType) -> str:
    """Get the input code arguments to a function as a string."""
    code_input = inspect.getouterframes(frame, 1)
    code_contexts = tuple(frame.code_context for frame in code_input)
    code_context_string = code_contexts[-1][0]
    function_call_strings = (
        search(fr"\.{func_name}\(([\w|\W]+?\))", code_context_string)
        .group(1)
    )
    return function_call_strings
```

This doesn't solve the chaining problem though...

2022-07-06 10:42 UTC, jamesgyoung commented on src/sds_data_model/constants.py
> +BNG = "OSGB 1936 / British National Grid"
```suggestion
BNG = "OSGB36 / British National Grid"
```
Rollback change to resolve conflict. [Solution](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/564956f3888d50e56e46606a97bf3b97d890773c/src/sds_data_model/constants.py#L5) already merged in #20.

2022-07-07 15:28 UTC, EFT-Defra commented on src/sds_data_model/table.py
> +        return query_output
Do we need both a `where` and a `query` method?

2022-07-07 15:39 UTC, EFT-Defra requested changes
Hi @danlewis85, @PiumiA, and @jpd-defra,

I think:

- you should remove the logging related functions as they've been moved to #31 
- you should add file suffixes for the other files `pandas.read_excel` can read
-  you don't have to handle HTTP/HTTPS here because headers can be passed to the `storage_options` parameter of `read_excel`, `read_csv`, `read_json`, and `read_parquet`
- you don't need both `where` and `query` methods
- you don't need the `replace` and `to_numerical` methods as you can pass a dictionary of column names and `lambda` expression the the `converter` parameter of `read_excel` and `read_csv`. Where these can't be used I think we need a generic `mutate` method for changing or adding columns.

2022-07-07 15:39 UTC, EFT-Defra commented on src/sds_data_model/table.py
> +    return code_input
The logging-related functions can be removed now the logic has been moved to #31

2022-07-11 18:50 UTC, danlewis85 commented on src/sds_data_model/table.py
> +        return query_output
I'll retain `where` then as `query` only allows for numerical conditions.

2022-07-11 18:51 UTC, danlewis85 commented on src/sds_data_model/table.py
> +            df = file_reader[suffix](data_path, **data_kwargs)
Interesting, in which case I'll remove in favour of the options given in the example above.

2022-07-11 18:52 UTC, danlewis85 commented on src/sds_data_model/table.py
> +        return numeric_output
Useful information, I will remove in favour of these methods.

2022-07-12 15:30 UTC, danlewis85 commented on src/sds_data_model/table.py
> +    return code_input
All logging removed from current code, to be reinstated with new logging decorator in new issue.

2022-07-12 15:33 UTC, danlewis85 commented
> Hi @danlewis85, @PiumiA, and @jpd-defra,
> 
> I think:
> 
> * you should remove the logging related functions as they've been moved to #31
> * you should add file suffixes for the other files `pandas.read_excel` can read
> * you don't have to handle HTTP/HTTPS here because headers can be passed to the `storage_options` parameter of `read_excel`, `read_csv`, `read_json`, and `read_parquet`
> * you don't need both `where` and `query` methods
> * you don't need the `replace` and `to_numerical` methods as you can pass a dictionary of column names and `lambda` expression the the `converter` parameter of `read_excel` and `read_csv`. Where these can't be used I think we need a generic `mutate` method for changing or adding columns.

Hi @EFT-Defra ,

We've discussed and applied all required changes. Yours to merge.

2022-07-13 15:31 UTC, EFT-Defra approved these changes

2022-07-13 15:31 UTC, merged