Improve public docstrings
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #220
Opened 2023-01-25 12:11 UTC by jpd-defra

This PR adds more detail to public facing docstrings for classes, methods and functions.

2023-01-25 15:56 UTC, jpd-defra commented
Fixes #214.

2023-01-26 14:15 UTC, jpd-defra commented
Fixes #214 and #210.

I think I branched this off some initial graph work Ed and I were doing, so there are a few graph related changes to satisfy tests. Mainly commenting out an old test which is now defunct.

2023-02-02 17:02 UTC, JamesKeny0n requested changes
Looks good. Just a couple of indentation issues to my eye.

2023-02-02 17:02 UTC, jamesgyoung commented on src/sds_data_model/raster.py
> +    _DatasetWrapper: Dataset
Add indentation.
```suggestion
    Attributes:
        dataset(Dataset): An xarray Dataset containing one or more DataArrays.

    Methods:
        from_files: Read in a raster from file at 10m cell size and
            British National Grid extent.

    Returns:
        _DatasetWrapper: Dataset
```

2023-02-02 17:02 UTC, jamesgyoung commented on src/sds_data_model/dataframe.py
> +        relating to the source data and transformations that have taken place.
Add indentation and `lookup` description.
```suggestion
        data (Union[SparkDataFrame, GroupedData]): Tabular data, optionally containing
            a geometry column.
        metadata (Metadata, optional): Object of class `Metadata` containing descriptive
            information relating to the dataset represented in `data`.
        lookup (Dict[str, Dict[Any, float]], optional): Dictionary of 
            `{column: value-map, ...}` for columns in the data. Not applied to the data. 
            Use of `categorize` will write the lookups used by the method to this
            attribute. This attribute is written to the output of `to_zarr`.
        graph (Digraph, optional): Object of class `Digraph` containing nodes and edges
            relating to the source data and transformations that have taken place.
```

2023-02-03 08:28 UTC, merged

2023-02-03 08:28 UTC, jpd-defra commented
Thanks @JamesKeny0n, closing and merging.