parsing single value mandatory elements
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #46
Opened 2022-07-14 21:25 UTC by PiumiA

Fixes #34:

Was able to identify which paths took to each element and test it on the Ramsar metadata xml file. This worked quite well. Only path unable to find was for the element spatial data service type.

2022-07-15 16:29 UTC, EFT-Defra requested changes
Good work but there's a few things you need to correct before we can merge this.

2022-07-15 16:29 UTC, EFT-Defra commented on src/sds_data_model/constants.py
> +    "gmd:MD_ScopeCode"
This is the the data quality scope, for lineage it would be:

```suggestion
    "gmd:lineage",
    "gmd:LI_Lineage",
    "gmd:statement",
    "gco:CharacterString",
```

2022-07-15 16:29 UTC, EFT-Defra commented on src/sds_data_model/constants.py
> +    "gmd:MD_Metadata",
Remove "gmd:MD_Metadata"

```suggestion
```

2022-07-15 16:29 UTC, EFT-Defra commented on src/sds_data_model/constants.py
> +    "gmd:MD_Metadata",
Remove "gmd:MD_Metadata"

```suggestion
```

2022-07-15 16:29 UTC, EFT-Defra commented on src/sds_data_model/constants.py
> +    "gmd:MD_Metadata",
Remove "gmd:MD_Metadata"

```suggestion
```

2022-07-15 16:29 UTC, EFT-Defra commented on src/sds_data_model/constants.py
> +    "gmd:MD_Metadata",
Remove "gmd:MD_Metadata"

```suggestion
```

2022-07-15 16:29 UTC, EFT-Defra commented on src/sds_data_model/constants.py
> +    "gmd:MD_Metadata",
Remove "gmd:MD_Metadata"

```suggestion
```

2022-07-15 16:29 UTC, EFT-Defra commented on src/sds_data_model/constants.py
> +    "gmd:MD_Metadata",
Remove "gmd:MD_Metadata"

```suggestion
```

2022-07-15 16:29 UTC, EFT-Defra commented on src/sds_data_model/metadata.py
> +from sds_data_model.constants import TITLE_XPATH, ABSTRACT_XPATH, LINEAGE_XPATH, METADATA_DATE_XPATH, METADATA_LANGUAGE_XPATH, SPATIAL_DATA_SERVICE_TYPE_XPATH,RESOURCE_TYPE_XPATH, FILE_IDENTIFIER_XPA
I think the spatial data service type is "dataset or series" but, as you say, there's nothing in the standard or the XML, so you can ignore it.

```suggestion
from sds_data_model.constants import TITLE_XPATH, ABSTRACT_XPATH, LINEAGE_XPATH, METADATA_DATE_XPATH, METADATA_LANGUAGE_XPATH, RESOURCE_TYPE_XPATH, FILE_IDENTIFIER_XPATH
```

2022-07-22 08:43 UTC, jpd-defra requested changes
This is looking very comprehensive, good work. There are a few bits of potential tidying/adding of documentation that could improve this PR before it's merged. I think `py.typed` is an accidental file that requires deletion too. 

Regarding testing, how is this implemented? Is the test run with `nox` when certain actions like push/merge are made? I'm asking more out of curiosity rather than requesting changes to the PR.

2022-07-22 08:43 UTC, jpd-defra commented on src/sds_data_model/constants.py
> +
As with other variables defined in the constants could you add a comment explaining these additional variables please?

2022-07-22 08:43 UTC, jpd-defra commented on src/sds_data_model/metadata.py
> +def _get_xpath(xpath: Union[str, List[str]]) -> str:
Not sure we've agreed on docstring style and whether we want both hidden/visible functions to have more comprehensive docstring coverage, e.g. descriptions of inputs/returns/raises. Ed told me about the [autodocstring ](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) VSCode addon which made it really painless. Maybe not essential at this stage but a "nice to have".

2022-07-22 08:43 UTC, jpd-defra commented on src/sds_data_model/metadata.py
> +@dataclass
Are the commented out variables such as `temporal_extent` for future work on this part of the package, or can they be removed?

2022-07-22 08:43 UTC, jpd-defra commented on src/sds_data_model/test.ipynb
> +{
As this is a notebook, i'm guessing it's a hangover from the development phase. Is it meant to be in the package? Please remove if not.

2022-07-22 08:43 UTC, jpd-defra commented on tests/test_metadata.py
> +from pathlib import Path
Great to see a test implemented! Nice one. I'm not sure what the convention on tests is, but I guess some docstrings at least for the `test_from_file` function would be appreciated please.

2022-08-01 08:48 UTC, EFT-Defra commented on src/sds_data_model/metadata.py
> +@dataclass
They're future work, they're GEMINI elements we're yet to implement.

2022-08-01 08:57 UTC, EFT-Defra commented on src/sds_data_model/constants.py
> +
Is `# A tuple of BoundingBox for BNG 100km grid squares.` not enough of an explanation?

2022-08-01 09:04 UTC, EFT-Defra commented on src/sds_data_model/metadata.py
> +def _get_xpath(xpath: Union[str, List[str]]) -> str:
I've added full Google Style docstrings (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) to `metadata.py`. The only person I thought might want something other than Google Style was @danlewis85, as I know he's used NumPy docstrings (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) before, but I think he said he's happy as long as we're consistent. I'll put something on the Teams channel to confirm.

Usually, I wouldn't add full docstrings (one line description, examples, args, returns, raises) to private functions but I think it's worthwhile here as we all need to be able to understand the internals of this package.

2022-08-01 09:04 UTC, EFT-Defra commented on src/sds_data_model/test.ipynb
> +{
Deleted.

2022-08-01 09:12 UTC, EFT-Defra commented on tests/test_metadata.py
> +from pathlib import Path
I've added a one line description to the `test_from_file` function. Generally, I follow the ['test_that')(https://testthat.r-lib.org/reference/test_that.html) approach, whereby, prefixing the description with "Test that <name of function>..." creates a human-understandable sentence but I'm not sure I always manage to follow that or if it's actually adding anything.

I'm very open to suggestions here!

2022-08-01 09:13 UTC, EFT-Defra commented
Closes #63

2022-08-02 07:18 UTC, jpd-defra commented on src/sds_data_model/constants.py
> +
Yep that's all good thanks.

2022-08-02 07:35 UTC, jpd-defra commented on tests/test_metadata.py
> +from pathlib import Path
I like the sound of that approach, and if it was applied to `test_from_file` would something like "Tests that GEMINI metadata is parsed correctly when read from an XML file" bet a better fit? 

I had a quick google and it seems it's another topic with varying opinions and approaches...one-liners seems like a good middle ground.

2022-08-02 07:36 UTC, jpd-defra reviewed
Thanks for this Ed. I'll be honest and say I'm not sure what my docstrings comment was referring to in the constants file! It's looking good now. I added a followup comment on test docstrings but happy for you to take it or leave it.

2022-08-03 09:41 UTC, merged