Jpd defra/issue40
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #48
Opened 2022-07-18 14:52 UTC by jpd-defra

## Overview

This PR implements a new hidden function called `_check_projection`. This function uses python's GDAL bindings to acquire the Spatial Reference information of an OGR-readable vector layer, and checks the Spatial Reference against a constant, created by the same bindings within `constants.py`. The function is called at the start of the `from_files` method in `VectorLayer`. 

## Things to note/consider

1. Previously, the Geopandas method `crs.name` was used to acquire projection information from the input file and compare against two strings in `constants.py`. The two strings were slight variations of the same CRS (EPSG:27700). I have only managed to test the function on this PR with input data which GeoPandas considers `OSGB36 / British National Grid` and not `OSGB 1936 / British National Grid`. However, I am farily confident that data with either of these CRS names (as deemed by GeoPandas) will have the same Spatial Reference information and therefore pass the check provided by `_check_projection`. 
2. If no layer name is provided as input by the user, then the projection of the 0th layer is checked by the function. 
3. Currently, a holding print statement is in place when the function succeeds. I imagine this will be replaced with a logging function to store the projection information of the source data.

2022-07-19 09:27 UTC, EFT-Defra requested changes
There's nothing wrong with you're approach but I'd like you to make some changes to the structure and documentation.

2022-07-19 09:27 UTC, EFT-Defra commented on src/sds_data_model/_vector.py
> +    vector_data: str, **data_kwargs
I don't think these parameter names accurately describe the arguments the function takes.

You're expecting a string path not some vector data and you don't need to clarify these key word arguments with a prefix because you're only expecting one set.

```suggestion
    path: str, **kwargs
```

2022-07-19 09:27 UTC, EFT-Defra commented on src/sds_data_model/_vector.py
> +    """This function acquires the 'projcrs' attribute from an OGR compatible vector file and checks whether it matches BNG projection strings used within the data model."""
We haven't really got into docstring style yet but I prefer [the Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) because I think it's more suited to long, narrow docstrings, when compared to [the `numpy` docstring style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy).

Either way, this docstring is too long. A single line function docstring should be less than 90 characters in length. A longer description can be included in the following paragraph.

Personally, I use the [autodocstring extension](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) to automagically generate Google-style docstrings.

However, we do need to discuss, as a dev team, what our approach to docstrings will be. If I was writing a public facing library, I wouldn't bother with full docstrings for private functions and would be happy with a single-line description. However, as we'll be interacting with the internals of this library, it might be worth add full docstrings to private as well as public functions.

2022-07-19 09:27 UTC, EFT-Defra commented on src/sds_data_model/_vector.py
> +        raise Exception("Input dataset not in British National Grid. Reproject before proceeding.")
I think that separating these two steps with comments suggests that they should be separate functions: a `_get_layer` function, which takes a string path and optional `kwargs` and returns an OGR layer, and a `_check_layer_projection` function, which takes an OGR layer and raises an error if it's not BNG.

This will increase reusability as the `_get_layer` function can be used in any circumstances where you want to get a layer (such as extracting the dtypes...)

2022-07-20 11:16 UTC, EFT-Defra commented
@jpd-defra do you need me to re-review this or do you need to make more changes?

2022-07-20 11:24 UTC, jpd-defra commented
> @jpd-defra do you need me to re-review this or do you need to make more changes?

I still need to implement your suggested changes.

2022-07-20 13:47 UTC, jpd-defra commented on src/sds_data_model/_vector.py
> +        raise Exception("Input dataset not in British National Grid. Reproject before proceeding.")
Thanks for your suggestions. I agree and have implemented in the latest commit. Does this resolve the issue?

2022-07-20 13:48 UTC, jpd-defra commented on src/sds_data_model/_vector.py
> +    """This function acquires the 'projcrs' attribute from an OGR compatible vector file and checks whether it matches BNG projection strings used within the data model."""
That's a handy extension - thanks. I used it to add some templates to my new functions and populated them accordingly. Does that solve the issue?

2022-07-27 15:29 UTC, EFT-Defra approved these changes
Thanks for making those changes!

2022-07-27 15:30 UTC, merged