Encode categorical variables before rasterisation
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #64
Opened 2022-07-22 15:30 UTC by s-flint-defra

This has been tested and working on local authority district data. Currently doesn't:

- Write lookup to the dataset.
- Do anything about a situation where a categorical column is defined but is already numeric.
- Any error catching.

I also removed a lot of code from previous sprints that is not needed any longer (mostly get dtype iterating through tiles).

2022-07-28 11:10 UTC, EFT-Defra requested changes
I'm suggesting some refactoring, splitting nested or otherwise complex comprehensions down into smaller functions, but the main things I'm asking you to do differently are:

1. Get the `dtype` from the categorical column and use it to update the schema
2. Recode on read instead of at rasterisation

We also need to implement this logic for `TiledVectorLayer`.

2022-07-28 11:10 UTC, EFT-Defra commented on src/sds_data_model/_vector.py
> +        return gpdf
As you're dropping `gpdf[f'{column}_code']` away, why not just over write it directly ? Also looking up the dictionary key from the value is quite complicated so I'd be tempted to split it up into a series of smaller functions.

```suggestion
def _get_index_of_category(
    category_lookup: CategoryLookup,
    category: str,
) -> int:
    return list(category_lookup.values()).index(category)


def _get_code_for_category(
    category_lookup: CategoryLookup,
    category: str,
) -> str:
    index = _get_index_of_category(
        category_lookup=category_lookup,
        category=category,
    )
    return list(category_lookup.keys())[index]


def _recode_categorical_strings_ed(
    gpdf: GeoDataFrame,
    column: str,
    category_lookups: CategoryLookups,
) -> GeoDataFrame:
    """Returns a GeoDataFrame where an integer representation of a categorical column specified by the user is assigned
    to the GeoDataFrame - string representation is dropped but mapping is stored in self.category_lookup."""
    gpdf.loc[:, column] = gpdf.loc[:, column].apply(
        lambda category: _get_code_for_category(
            category_lookup=category_lookups[column],
            category=category,
        )
    )
    return gpdf
```

2022-07-28 11:10 UTC, EFT-Defra commented on src/sds_data_model/_vector.py
> +        return cat_lookup
I have five suggestions here: 

1. You could use [`pyogrio.read_dataframe`](https://pyogrio.readthedocs.io/en/latest/api.html#pyogrio.read_dataframe) instead of `geopandas.read_file`, which would allow you to read only the columns you're interested in.
2. The comprehensions are quite dense, so you could break them down into smaller functions.
3. You could also get the integer dtype from the categorical column here
4. You could simplify the function signatures by using [type aliases](https://docs.python.org/3.8/library/typing.html#type-aliases)
5. You could make `data_kwargs` optional and `None` by default

```suggestion
from typing import Tuple, Optional

from pandas import DataFrame, Series

CategoryLookup = Dict[str, Dict[int, str]]
CategoryLookups = Dict[str, CategoryLookup]
Schema = Dict[str, str]

def _get_categorical_column(
    df: DataFrame,
    column_name: str,
) -> Series:
    column = df.loc[:, column_name]
    return column.astype("category")

def _get_category_lookup(
    categorical_column: Series,
) -> CategoryLookup:
    return {index: category for index, category in enumerate(categorical_column.cat.categories)}

def _get_category_dtype(
    categorical_column: Series,    
) -> str:
    return str(categorical_column.cat.codes.dtype)

def _get_categories_and_dtypes(
    data_path: str,
    convert_to_categorical: List[str],
    data_kwargs: Optional[Dict[str, str]] = None,
) -> Tuple[CategoryLookups, Schema]:
            """Category and dtype looks for each column."""
    if data_kwargs:
        df = read_dataframe(
            data_path,
            read_geometry=False,
            columns=[convert_to_categorical],
            **data_kwargs,
        )
    else:
        df = read_dataframe(
            data_path,
            read_geometry=False,
            columns=[convert_to_categorical],
        )
    categorical_columns = tuple(
        (
            column_name,
            _get_categorical_column(
                df=df,
                column_name=column_name,
            ),
         ) for column_name in convert_to_categorical
    )
    category_lookups = {
        column_name: _get_category_lookup(categorical_column) for column_name, categorical_column in categorical_columns
    }
    category_dtypes = {
        column_name: _get_category_dtype(categorical_column) for column_name, categorical_column in categorical_columns
    }
    return (category_lookups, category_dtypes)
```

2022-07-28 11:10 UTC, EFT-Defra commented on src/sds_data_model/vector.py
> +
As discussed, I think you should recode the categorical columns and update the schema on read, instead of waiting until rasterisation.

```suggestion
        schema = {
            k: v
            for k, v in zip(
                *(read_info(data_path).get(key) for key in ["fields", "dtypes"])
            )
        }

        if convert_to_categorical:
            category_lookups, dtype_lookup = _get_categories_and_dtypes(
                data_path=data_path,
                convert_to_categorical=convert_to_categorical,
                data_kwargs=data_kwargs,
            )
            for column in convert_to_categorical:
                gpdf = _recode_categorical_strings(
                    gpdf=gpdf,
                    column=column,
                    category_lookups=category_lookups,
                )
            schema = {**schema, **dtype_lookup}
        else:
            category_lookups = None
```

2022-07-29 08:09 UTC, s-flint-defra commented on src/sds_data_model/_vector.py
> +        return gpdf
Agreed inverting the intended use of a dictionary is messy and hard to read (it was hard to write!). Happy with these changes so accepting suggestion.

2022-07-29 08:30 UTC, s-flint-defra commented on src/sds_data_model/_vector.py
> +        return cat_lookup
This is very neat - happy with the changes so will accept.

2022-08-01 08:03 UTC, merged