Setup linting with flake8 and plugins
Defra-Data-Science-Centre-of-Excellence/sds-data-model pull request #65
Opened 2022-07-27 13:47 UTC by jpd-defra

This pull request adds the relevant configuration to run flake8 linting as part of a nox-driven pipeline. 

Ideally it could do with testing as part of the CI pipeline, to check that the configuration is correct. 

It also includes a markdown file describing the flake8 module, why and how to use it.

2022-08-11 13:23 UTC, EFT-Defra requested changes
A couple of very major corrections

2022-08-11 13:23 UTC, EFT-Defra commented on .flake8
> +application-import-names = esa_geo_utils,tests
This should be our package

```suggestion
application-import-names = sds_data_model,tests
```

2022-08-11 13:23 UTC, EFT-Defra commented on markdown/linting.md
> +This project uses GitHub Actions for Continuous Integration. The CI workflow is defined in `.github/workflows/python-package.yml`. This workflow will run the  `black` and `isort` sessions as part of
```suggestion
This project uses GitHub Actions for Continuous Integration. The CI workflow is defined in `.github/workflows/python-package.yml`. This workflow will run the  `lint` job, whenever code is pushed to the `develop` branch or pull requests into `develop` are triggered.
```

2022-08-16 10:41 UTC, jpd-defra commented
Thanks @EFT-Defra, those two suggestions have been accepted. I won't mess about with resolving those conflicts for now...

2022-08-16 19:09 UTC, EFT-Defra approved these changes
Thanks for making those changes!

2022-08-16 19:09 UTC, merged